### ISSUE TITLE
OAuth to Fitbit fails in BioMarin pkYOU Study

### ISSUE THREAD

**Issue by DanWebster** [Sage-Bionetworks/BridgeServer2#296]
Potentially related to the issue that is fixed with PR #295 

In BioMarin pkYOU app, when attempting to OAuth to Fitbit during study enrollment, fails with the message:
"Attempting to reauth an account with a password but with no email, phone, or externalId". (screenshot)
<img width="1084" alt="Screen Shot 2020-11-19 at 11 58 15 AM" src="https://user-images.githubusercontent.com/3682103/99718110-3c7cbe80-2a5f-11eb-95e0-b7b0c4694b1f.png">

Note that owing to the current complications with building in a simulator, I cannot run the app without a pre-cached User Profile on my device so I do not know the externalID that is being used to generate the error.

To reproduce from API calls instead of the app, the following could be used:
externalID = 9999-0003 (a valid test account, but created with the old BSM externalID creation
fitbit username: danwebster13@gmail.com
fitbit password: sageBionetworksT3$t

**Priority level**: Medium/low.  As the pkYOU study is currently paused for new enrollments, this mechanism is not likely to be called because it is only applicable during enrollment. However, if someone gets logged out for any reason, their data pull would be failing silently to the user.  In looking at the data coming through, this does not appear to be affecting active users that are only getting their refresh token. With all that being said, if the PR #295 fix is able to be cross-applied to the OAuth mechanism, I want to surface it here so that this doesn't get lost in the shuffle once enrollment becomes unpaused.

@alxdarksage @DwayneJengSage

**Comment by alxdarksage** [comment]
If this is still an issue, let's file in JIRA, otherwise, let's close this.
